export const PATIENT_DATA_REQUEST = "PATIENT_DATA_REQUEST";
export const PATIENT_DATA_SUCCESS = "PATIENT_DATA_SUCCESS";
export const PATIENT_DATA_FAILURE = "PATIENT_DATA_FAILURE";
// Register
export const DOCTOR_DATA_REQUEST = "DOCTOR_DATA_REQUEST";
export const DOCTOR_DATA_SUCCESS = "DOCTOR_DATA_SUCCESS";
export const DOCTOR_DATA_FAILURE = "DOCTOR_DATA_FAILURE";
// Login

export const LOGIN_DATA_REQUEST = "LOGIN_DATA_REQUEST";
export const LOGIN_DATA_SUCCESS = "LOGIN_DATA_SUCCESS";
export const LOGIN_DATA_FAILURE = "LOGIN_DATA_FAILURE";

// update
export const UPDATE_DATA_REQUEST = "UPDATE_DATA_REQUEST";
export const UPDATE_DATA_SUCCESS = "UPDATE_DATA_SUCCESS";
export const UPDATE_DATA_FAILURE = "UPDATE_DATA_FAILURE";
